#! /bin/sh
### BEGIN INIT INFO
# Provides:          bitcalm_daemon
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Bitcalm backup daemon
# Description:       Bitcalm backup daemon
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DESC="Bitcalm backup service"
NAME=bitcalmd
DAEMON=`command -v bitcalm`
PIDFILE=/var/run/bitcalmd.pid
SCRIPTNAME=/etc/init.d/$NAME

[ -x "$DAEMON" ] || exit 0

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

if [ -r /etc/init.d/functions ]; then
	. /etc/init.d/functions
	status=status
else
	. /lib/init/vars.sh
	. /lib/lsb/init-functions
	status=status_of_proc
fi

do_start()
{
	if [ -e $PIDFILE ]; then
		$status -p $PIDFILE $DAEMON "$NAME process" && status="0" || status="$?"
		if [ $status = "0" ]; then
			return 1
		fi
	fi
	bitcalm start && return 0 || return 2
}

do_stop()
{
	if [ -e $PIDFILE ]; then
		bitcalm stop && return 0 || return 2
	else
		return 1
	fi
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && echo "Starting ${NAME}"
	do_start
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping ${NAME}"
	do_stop
	;;
  status)
	$status "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  restart|force-reload)
	log_daemon_msg "Restarting ${NAME}"
	do_stop
	case "$?" in
	  0|1)
		do_start
		;;
	  *)
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
